version: "3.8"
services:
  vault-server:
    image: vault:latest
    ports:
      - "8200:8200"
    environment:
      VAULT_LOCAL_CONFIG: '{"storage": {"file": {"path": "/vault/file"}}, "listener": [{"tcp": { "address": "0.0.0.0:8200", "tls_disable": true}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h", "ui": true}'
      # VAULT_ADDR: "http://0.0.0.0:8200"
      # VAULT_API_ADDR: "http://0.0.0.0:8200"
      # VAULT_DEV_ROOT_TOKEN_ID: "vault-plaintext-root-token"
    cap_add:
      - IPC_LOCK

    # vault-server_1  | Unseal Key: U4FbmTMzZEWcz1h91M3GkEx0K1TBS29Z7l47x/DZ/N0=
    # vault-server_1  | Root Token: vault-plaintext-root-token